fornecedores = {
    'CSA-BH': {
        'CANTINA FREITAS',
        'EXPRESSA TURISMO LTDA',
        'ACREDITE EXCURSÕES E EXPOSIÇÕES INTINERANTE LTDA',
        'LEAL VIAGENS E TURISMO',
        'MINASCOPY NACIONAL EIRELI',
        'OTIMIZA VIGILÂNCIA E SEG. PATRIMONIAL',
        'PETRUS LOCACAO E SERVICOS LTDA',
        'REAL VANS LOCAÇÕES',
        'AC TRANSPORTES E SERVIÇOS LTDA - ACTUR',
        'TRANSCELO TRANSPORTES LTDA',
        'AC Transportes e Serviços LTDA'
    },
    'CSA-CT': {
        'EXPRESSA TURISMO LTDA',
        'MINASCOPY NACIONAL EIRELI',
        'OTIMIZA VIGILÂNCIA E SEG. PATRIMONIAL',
        'PETRUS LOCACAO E SERVICOS LTDA',
        'NUTRIMIX - EXCELÊNCIA EM ALIMENTAÇÃO',
        'MODERNA TURISMO LTDA',
        'ELEVADORES ATLAS SCHINDLER',
        'ACTUR TURISMO'
    },
    'CSA-NL': {
        'EXPRESSA TURISMO LTDA',
        'MINASCOPY NACIONAL EIRELI',
        'OTIMIZA VIGILÂNCIA E SEG. PATRIMONIAL',
        'PETRUS LOCACAO E SERVICOS LTDA',
        'REAL VANS LOCAÇÕES',
        'TRANSCELO TRANSPORTES LTDA',
        'MODERNA TURISMO LTDA',
        'SALADA & TAL ( PAOLA OLIVEIRA COSTA )ELEVADORES ATLAS SCHINDLER LTDA',
        'FORMA CONHECER',
        'THYSSENKRUPP EVEVADORES'
    },
    'CSA-GZ': {
        'EXPRESSA TURISMO LTDA',
        'JD CONSERVAÇÃO E SERVIÇOS',
        'MINASCOPY NACIONAL EIRELI',
        'OTIMIZA VIGILÂNCIA E SEG. PATRIMONIAL',
        'REAL VANS LOCAÇÕES',
        'AC TRANSPORTES E SERVIÇOS LTDA - ACTUR',
        'NUTRIMIX - EXCELÊNCIA EM ALIMENTAÇÃO',
        'JD CONSERVAÇÃO E SERVIÇOS',
        'MODERNA TURISMO LTDA',
        'CAMPOS DE MINAS SERV. ORG. PROG.TURÍSTICOS',
        'ELEVADORES ATLAS SCHINDLER',
        'ACCESS GESTÃO DE DOCUMENTOS LTDA'
    },
    'EPSA': {
        'EXPRESSA TURISMO LTDA',
        'AC TRANSPORTES E SERVIÇOS LTDA - ACTUR',
        'MODERNA TURISMO LTDA',
        'GULP SÃO TOMAS',
        'ELEVAÇO LTDA'
    },
    'ILALI': {
        'PHP SERVICE EIRELI'
    },
    'SIC SEDE': {
        'ACCESS GESTÃO DE DOCUMENTOS LTDA',
        'QA - IT ANSWER - CONSULTORIA - N1',
        'QA - IT ANSWER - CONSULTORIA - N2'
    }
}